services:
  frontend-dev:
    image: adalmia/sensai-frontend:dev
    ports:
      - "8502:3000"
    depends_on:
      backend-dev:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sensai-network-dev

  backend-dev:
    image: adalmia/sensai-ai:v2-dev
    volumes:
      - /appdata_dev:/appdata
    ports:
      - "8002:8001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - sensai-network-dev
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FOLDER_NAME=${S3_FOLDER_NAME}
      - ENV=${ENV}
      - BUGSNAG_API_KEY=${BUGSNAG_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SLACK_USER_SIGNUP_WEBHOOK_URL=${SLACK_USER_SIGNUP_WEBHOOK_URL}
      - SLACK_COURSE_CREATED_WEBHOOK_URL=${SLACK_COURSE_CREATED_WEBHOOK_URL}
      - SLACK_USAGE_STATS_WEBHOOK_URL=${SLACK_USAGE_STATS_WEBHOOK_URL}
      - SLACK_ALERT_WEBHOOK_URL=${SLACK_ALERT_WEBHOOK_URL}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_TRACING_ENVIRONMENT=${LANGFUSE_TRACING_ENVIRONMENT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BQ_PROJECT_NAME=${BQ_PROJECT_NAME}
      - BQ_DATASET_NAME=${BQ_DATASET_NAME}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}

  public-api-dev:
    image: adalmia/sensai-ai:v2-dev
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.public:app --host 0.0.0.0 --port 8001"
    volumes:
      - /appdata_dev:/appdata
    restart: unless-stopped
    ports:
      - "8005:8001"
    environment:
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_FOLDER_NAME=${S3_FOLDER_NAME}
      - ENV=${ENV}
      - BUGSNAG_API_KEY=${BUGSNAG_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SLACK_USER_SIGNUP_WEBHOOK_URL=${SLACK_USER_SIGNUP_WEBHOOK_URL}
      - SLACK_COURSE_CREATED_WEBHOOK_URL=${SLACK_COURSE_CREATED_WEBHOOK_URL}
      - SLACK_USAGE_STATS_WEBHOOK_URL=${SLACK_USAGE_STATS_WEBHOOK_URL}
      - SLACK_ALERT_WEBHOOK_URL=${SLACK_ALERT_WEBHOOK_URL}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_TRACING_ENVIRONMENT=${LANGFUSE_TRACING_ENVIRONMENT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - BQ_PROJECT_NAME=${BQ_PROJECT_NAME}
      - BQ_DATASET_NAME=${BQ_DATASET_NAME}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}

networks:
  sensai-network-dev:
    driver: bridge
