services:
  frontend:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:3000"
    restart: unless-stopped
    environment:
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - WS_PUBLIC_ORIGIN=${WS_PUBLIC_ORIGIN}
